version: '3.8'
services:
  app:
    build: .
    restart: always
    expose:
      - "3000"
    networks:
      - coolify
    environment:
      - HOST=${HOST}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - BASE_URL=${BASE_URL}
      - MODEL_NAME=${MODEL_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

networks:
  coolify:
    external: true
